# Generated by Django 2.2.2 on 2019-06-29 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_birth',
            field=models.CharField(default='Nigeria', max_length=50),
        ),
    ]
