# Generated by Django 2.2.2 on 2019-06-29 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190629_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of Birth'),
        ),
    ]
